### ISSUE TITLE
Limit lenght of input

### ISSUE THREAD

**Issue by mr-bammby** [VladDrgm/Transcendence#176]
- [x] Settings username
- [x] Login username
- [x] Channel name

**Comment by mr-bammby** [comment]
@VladDrgm wouldn it be easyer to do that in backend? Just no accepting input if the input is too long?

**Comment by VladDrgm** [comment]
@mr-bammby I wasn't sure where to limit this - which input do you mean specifically?
Also, validation should be done both frontend and backend.

**Comment by VladDrgm** [comment]
Add frontend level of checks - 15 characters maximum.
