### ISSUE TITLE
Implement status and status change

### ISSUE THREAD

**Issue by mr-bammby** [VladDrgm/Transcendence#183]
- [x] Logout tab (offline)
- [x] Logout button (offline)
- [x] Close browser tab (offline)
- [x] Change tab (online)
- [x] Log in  (online)
- [x] Sign up (online)
- [x] Join game (in queue)
- [x] Start game (in game)
- [x] End game(online)

**Comment by VladDrgm** [comment]
@timygerdes I can add an endpoint to change status from 'online' to 'in game' to 'offline'.
You will have to call it for the specific situations at login and logout.

@mluik-git you will have to call it during a game.

Please comment her eif this sounds good.

**Comment by mluik-git** [comment]
I can add status change to "in game" after joining a game queue, and change it to "online" after leaving the queue or leaving the game session. I will not be able to handle setting "offline" states from inside the game: for the game, it's always the same when a player leaves the game/queue, the game doesn't know if the player closed browser or maybe just went to leaderboards.

**Comment by ksura12** [comment]
Status Changes in Game added

**Comment by ksura12** [comment]
the method in the frontend is postUserStatus(status: string, user: User)
feel free to use this to make status update calls to the API

**Comment by timygerdes** [comment]
Done for login/logout, app state changes like leaving tab/window, closing tab

**Comment by VladDrgm** [comment]
After logging in, my status is 'offline' , so not updating to 'online'.
After closing tab, my status is 'online', so not updating to 'offline'.
When logging out via the top button (not the one from settigns), my status is not updated to 'offline'.

**Comment by VladDrgm** [comment]
Login / logout works. Sign up works.

Closing the browser still doesn't. - we should appear offline if we close the browser
