### ISSUE TITLE
Dobule check docker-compose up --build

### ISSUE THREAD

**Issue by mluik-git** [VladDrgm/Transcendence#207]
During testing the initial isntallation of our project, I found the following: 

- Both "make" and "docker-compose up --build" start the building process and finish it, but there is no prompt for env, thus the first run of the software fails. 
- After having added the .env files manually in the pong_frontend and pong_backend folders, and the running either "make" or "docker-compose up --build" again, the backend runs normally, but frontend gives following error: 

frontend_1  | 
frontend_1  | > pong_frontend@0.1.0 start /usr/src/app
frontend_1  | > react-scripts start
frontend_1  | 
backend_1   | 
backend_1   | > pong_backend@0.0.1 start /usr/src/app
backend_1   | > nest start
backend_1   | 
frontend_1  | internal/modules/cjs/loader.js:357
frontend_1  |       throw err;
frontend_1  |       ^
frontend_1  | 
frontend_1  | Error: Cannot find module '/usr/src/app/node_modules/react-refresh/index.js'. Please verify that the package.json has a valid "main" entry
frontend_1  |     at tryPackage (internal/modules/cjs/loader.js:349:19)
frontend_1  |     at Function.Module._findPath (internal/modules/cjs/loader.js:562:18)
frontend_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:917:27)
frontend_1  |     at Function.resolve (internal/modules/cjs/helpers.js:113:19)
frontend_1  |     at Object.<anonymous> (/usr/src/app/node_modules/@pmmmwh/react-refresh-webpack-plugin/lib/utils/injectRefreshLoader.js:16:47)
frontend_1  |     at Module._compile (internal/modules/cjs/loader.js:1114:14)
frontend_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
frontend_1  |     at Module.load (internal/modules/cjs/loader.js:979:32)
frontend_1  |     at Function.Module._load (internal/modules/cjs/loader.js:819:12)
frontend_1  |     at Module.require (internal/modules/cjs/loader.js:1003:19) {
frontend_1  |   code: 'MODULE_NOT_FOUND',
frontend_1  |   path: '/usr/src/app/node_modules/react-refresh/package.json',
frontend_1  |   requestPath: 'react-refresh'
frontend_1  | }
frontend_1  | npm ERR! code ELIFECYCLE
frontend_1  | npm ERR! errno 1
frontend_1  | npm ERR! pong_frontend@0.1.0 start: `react-scripts start`
frontend_1  | npm ERR! Exit status 1
frontend_1  | npm ERR! 
frontend_1  | npm ERR! Failed at the pong_frontend@0.1.0 start script.
frontend_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
frontend_1  | 
frontend_1  | npm ERR! A complete log of this run can be found in:
frontend_1  | npm ERR!     /root/.npm/_logs/2023-10-01T14_43_38_464Z-debug.log
tr_test_02_frontend_1 exited with code 1

- After running the front-end manually from the folder with npm start, it: 
1. starts normally and runs for the "make" build version, and 
2. gives the following error for the "docker-compose up --build" version: 

> pong_frontend@0.1.0 start
> react-scripts start

sh: 1: react-scripts: not found

**Comment by VladDrgm** [comment]
Fixed (at least works for me now)
