### ISSUE TITLE
Block button dose not change its function.

### ISSUE THREAD

**Issue by mr-bammby** [VladDrgm/Transcendence#231]

**Comment by ksura12** [comment]
What exactly is the issue ?

**Comment by mr-bammby** [comment]
It was problem for block on profiles
Seems like backend always returns message that this user isn't blocked

**Comment by mr-bammby** [comment]
@VladDrgm

**Comment by VladDrgm** [comment]
@ksura12 fixed. The whole Blocked domain is now revamped. Please check with me if something is unclear - but the endpoints are fully functional and the return values have slightly changed.
If you wish to see the return values and I am not available, check Swagger. I should be available today after 18:00ish.
