### ISSUE TITLE
When leaving a channel, a user has to be removed form channel users or admins

### ISSUE THREAD

**Issue by VladDrgm** [VladDrgm/Transcendence#271]
When leaving a channel - private or not, the user has to be deleted from the Channel Users or Channel Admins (if he is an admin).
If the owner leaves the channel - the channel should maybe be deleted alongside all users and all admins.

We have the endpoints, but the frontend doesn't implement them.

**Comment by ksura12** [comment]
fixed by deleting admin check from the method of adding User t private Channel
